# Generated by Django 4.2.6 on 2023-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='year',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
