# Generated by Django 4.2.6 on 2023-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='origin',
            field=models.TextField(),
        ),
    ]
